version: '3'

services:
  demp-airflow:
    image: demp-airflow:latest
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone
  demp-smtp:
    image: bytemark/smtp
    restart: always